#!/bin/sh

# First argument contains path to header files
if [ $# -gt 0 ]
then
	prefix=$1
else
	prefix=.
fi

cat <<EOF
/*
 * Automatically generated by extract_controls.sh
 * DO NOT EDIT
 *
 * This file calls the C pre-processor macro CONTROL for
 * every control present in tintamp
 */

#ifndef CONTROL_SEPARATOR
#define USING_DEFAULT_CONTROL_SEPARATOR
#define CONTROL_SEPARATOR ,
#endif

EOF

cat $prefix/*.h | \
awk '/_CONTROL_MIN,/ { on=1 } /_CONTROL_MAX/ { on=0 } on==1 { print $1 }' |
cut -d, -f1 |
grep -v '^TT_TEMPLATE_' |
sed -e 's/^/CONTROL(/' -e 's/$/) CONTROL_SEPARATOR/'

cat <<EOF

#ifdef USING_DEFAULT_CONTROL_SEPARATOR
#undef USING_DEFAULT_CONTROL_SEPARATOR
#undef CONTROL_SEPARATOR
#endif
EOF
