#!/bin/sh

cat <<EOF > controls.h
/*
 * Automatically generated by extract_controls.sh
 * DO NOT EDIT
 *
 * This file calls the C pre-processor macro CONTROL for
 * every control present in tintamp
 */

#ifndef CONTROL_SEPARATOR
#define USING_DEFAULT_CONTROL_SEPARATOR
#define CONTROL_SEPARATOR ,
#endif

EOF

cat include/libtt/*.h | \
awk '/_CONTROL_MIN,/ { on=1 } /_CONTROL_MAX/ { on=0 } on==1 { print $1 }' |
cut -d, -f1 |
grep -v '^TT_TEMPLATE_' |
sed -e 's/^/CONTROL(/' -e 's/$/) CONTROL_SEPARATOR/' >> controls.h

cat <<EOF >> controls.h

#ifdef USING_DEFAULT_CONTROL_SEPARATOR
#undef USING_DEFAULT_CONTROL_SEPARATOR
#undef CONTROL_SEPARATOR
#endif
EOF
